### ISSUE TITLE
lets pass as task / action

### ISSUE THREAD

**Issue by Lomet** [The-Poolz/Net.Urlify#7]
https://github.com/The-Poolz/Net.Urlify/blob/a1b0941a7152b39fa57c0986f15b7b85740a7a95/src/Net.Urlify/Extensions/ObjectExtensions.cs#L32-L37

**Comment by Lomet** [comment]
or regex string

**Comment by ArdenHide** [comment]
https://github.com/The-Poolz/Net.Urlify/issues/8
